// // date type        variable name          value
//    string                color =          'Red';


// string color_y = 'yellow';

// System.debug('color: '+ color + 'and color_Y :'+ color_y);
// // color : color(red)
// // color_y : color_y(yellow)

String my_name= 'Merdan';
String lastname= 'Ananyev';
Integer age = 23;


System.debug('allamyrat');

System.debug('My Name: ' + my_name); // print

System.debug('Surname: ' + lastname);
System.debug('I am ' + age + ' years old');

